#!/bin/bash
#
# bootstrap installs things.

#!/bin/bash

# -- Overrides
# You can create files to override the following configuration files:
#
# environment.defaults.sh = environment.sh *** CHECK THE FILE CONFIG.DEFAULTS.SH FOR MORE INSTRUCTIONS
# .brew_packages.defaults = .brew_packages
# .composer_packages.defaults = .composer_packages 
# .npm_packages.defaults = .npm_packages 
# ---

echo 'Bootstrap terminal'
echo '------------------'
echo 'This will reset your terminal. Are you sure you want to to this? (y/n) '
read -p 'Answer: '  reply

if [[ $reply =~ ^[Yy]$ ]] || [[ "$reply" = "yes" ]] || [[ "$reply" = "YES" ]]
then
	source ~/.dotfiles/base.sh

	install
fi
