#!/bin/bash

source helpers.sh
source installers.sh
source config.defaults.sh
source config.sh
source shell/.aliases

function install
{
    check_variables
    
    # configure_macos 

    # configure_git

    # install_homebrew

    # update_homebrew

    # install_hushlogin

    # install_ohmyzsh

    # install_global_gitignore

    # install_zsh_prefs

    # install_vim_prefs

    # install_yarn_prefs

    # install_ohmyzsh_themes ### looks line this one is not working anymore

    # install_powerline_fonts ### looks like the current fix for oh my zsh fonts
    
    # install_z

    # install_php

    # install_composer

    # install_node

    # install_pkg_config

    # install_wget 

    # install_httpie

    # install_ncdu

    install_hub
    
    # install_ack
    
    # install_doctl
    
    # install_imagemagick

    # install_memcached
    
    # install_redis

    # install_postgresql

    # install_mysql

    # install_yarn

    # install_ghostscript

    # install_mackup

    # install_zsh_autosuggestions
    
    # install_quicklook_plugins

    # install_autoconf

    # install_xcode_select

    # install_php_pear

    # install_php_xdebug

    # install_php_redis

    # install_php_imagick

    #  install_laravel_envoy

    # install_spatie_phpunit_watcher

    # install_spatie_mixed_content_scanner_cli

    # install_joe

    # install_nginx

    # install_dnsmasq

    # install_laravel_valet

    install_prettier

    display_instructions    
}

install
display_errors
